### PR TITLE
Usability improvements

### PR DESCRIPTION
**Pull request by tenox7**
- Changed buttons from text to icons with tooltips
- Game now asks you what to do when starts
- Warning of losing changes when exiting

### CODE REVIEW

**Comment by Miragecoder** [comment]
This is lovely. I truly was laughing out loud that you guys did some improvements to my hobby project. Great additions. I'm accepting the changes! 😄

**Comment by tenox7** [comment]
Thanks for accepting the changes. I think it's a pretty cool version of SimCity like game for Windows. It should be more popular!

**Comment by Miragecoder** [comment]
Thanks in return! Maybe I should rekindle my interest into this project as well; it sure was fun to build. 😄

**Comment by tenox7** [comment]
People play classic SimCity in DosBox on Windows. I think this is more convenient.

**Pull request merged**
